### ISSUE TITLE
Install programs

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/mimm4750g#2]
Currently the VM is running Fedora 28 and has no additional programs.  For instance, `/usr/local/bin` is empty.  Additional packages should be installed using `yum` instead of `apt`, but the syntax is similar.  The default programs that come with Fedora include:
* Python 2.7.15
* Python 3.6.6
* git 2.17.2
* perl 5.26.2

@horaciobam and @mavino, can you come up to get a temporary password to the VM, log in and change your password, and start installing programs we need for the course?  This will include:
* [x] Java
* [x] R
* [x] HyPhy
* [x] BEAST
* [x] bowtie2
* [x] mafft
* [x] muscle
* [x] fasttree2
* [x] STAR
* [x] R library Rsubread
* [x] HTseq
* [x] DESeq2

* **add other packages you need to this list**

**Comment by mavino** [comment]
Installed glibc-static required by STAR
```
sudo yum install glibc-static
```

**Comment by mavino** [comment]
Installed STAR

**Comment by mavino** [comment]
```
sudo yum install R-devel
```
Installed Rsubread library
```
sudo R CMD INSTALL /home/mavino/src/Rsubread_1.32.2.tar.gz
```

**Comment by mavino** [comment]
```
sudo yum groupinstall "Development Tools"
sudo yum install python-devel numpy python-matplotli
```
Installed HTseq, run it from an interactive python as
```
import HTseq
```
or simply type one of its python scripts like htseq-counts

**Comment by mavino** [comment]
```
sudo yum -y install libcurl-devel
```

**Comment by mavino** [comment]
Installed R library RCurl (required by DESeq2)

**Comment by mavino** [comment]
for DESeq2 R library
```
dnf install libxml2-devel 
```

Installed also R libraries S4Vectors, IRanges, SummarizedExperiment, BiocParallel, Biobase, GenomicRanges, locfit, ggplot2, Hmisc, Rcpp for DESeq2 which was installed right after
